[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=PhononBackend
MimeType=@PHONON_VLC_MIME_TYPES@;
X-KDE-Library=phonon_vlc
X-KDE-PhononBackendInfo-InterfaceVersion=1
X-KDE-PhononBackendInfo-Version=@PHONON_VLC_VERSION@
X-KDE-PhononBackendInfo-Website=http://www.videolan.org/
Icon=vlc
InitialPreference=20

Name=VLC
Name[ca]=VLC
Name[ca@valencia]=VLC
Name[cs]=VLC
Name[de]=VLC
Name[en_GB]=VLC
Name[es]=VLC
Name[eu]=VLC
Name[fi]=VLC
Name[fr]=VLC
Name[gl]=VLC
Name[id]=VLC
Name[it]=VLC
Name[ko]=VLC
Name[nb]=VLC
Name[nl]=VLC
Name[nn]=VLC
Name[pt_BR]=VLC
Name[sk]=VLC
Name[sr]=ВЛЦ
Name[sr@ijekavian]=ВЛЦ
Name[sr@ijekavianlatin]=VLC
Name[sr@latin]=VLC
Name[sv]=VLC
Name[uk]=VLC
Name[x-test]=xxVLCxx

Comment=Phonon VLC backend
Comment[ca]=Dorsal del VLC pel Phonon
Comment[ca@valencia]=Dorsal del VLC pel Phonon
Comment[cs]=Podpůrná vrstva VLC
Comment[de]=Phonon-Treiber für VLC
Comment[en_GB]=Phonon VLC backend
Comment[es]=Motor VLC para Phonon
Comment[eu]=Phonon VLC bizkarraldekoa
Comment[fi]=Phonon VLC -taustajärjestelmä
Comment[fr]=Module VLC pour Phonon
Comment[gl]=Infraestrutura de VLC para Phonon
Comment[id]=Backend phonon VLC
Comment[it]=Motore VLC di Phonon
Comment[ko]=Phonon VLC 백엔드
Comment[nb]=Phonon VLC-motor
Comment[nl]=VLC-backend van Phonon
Comment[nn]=VLC-motor for Phonon
Comment[pt_BR]=Infraestrutura VLC do Phonon
Comment[sk]=Backend Phonon VLC
Comment[sr]=ВЛЦ као позадина Фонона
Comment[sr@ijekavian]=ВЛЦ као позадина Фонона
Comment[sr@ijekavianlatin]=VLC kao pozadina Phonona
Comment[sr@latin]=VLC kao pozadina Phonona
Comment[sv]=Phonon VLC-gränssnitt
Comment[uk]=Модуль VLC Phonon
Comment[x-test]=xxPhonon VLC backendxx
